sandbox_mode = "workspace-write"

[mcp_servers.datadog-eu]
url = "https://mcp.datadoghq.eu/api/unstable/mcp-server/mcp?toolsets=core"

[mcp_servers.datadog-us]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp?toolsets=core"
