version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
