packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "web"
  - "worker"
  - "packages/**"
  - "ee"
# 8 day delay for new dep upgrades to reduce supply chain attack risk
minimumReleaseAge: 11520
# TODO: remove exclusions below!
# the exclusions are temporary so that we can set the 8 day limit without downgrading packages.
# this list is version-specific
minimumReleaseAgeExclude:
  - "picomatch@4.0.4"
  - "graphql@16.13.2"
  - "use-sync-external-store@1.6.0"
  - "release-it@19.2.4"
  - "@codemirror/language@6.12.3"
  - "@sentry/core@10.46.0"
  - "@sentry/node-core@10.46.0"
  - "@sentry-internal/browser-utils@10.46.0"
  - "@sentry-internal/replay@10.46.0"
  - "@sentry/opentelemetry@10.46.0"
  - "@sentry-internal/feedback@10.46.0"
  - "@sentry-internal/replay-canvas@10.46.0"
  - "@sentry/browser@10.46.0"
  - "@sentry/node@10.46.0"
  - "@sentry/react@10.46.0"
  - "@sentry/vercel-edge@10.46.0"
  - "@sentry/nextjs@10.46.0"
  - "@opentelemetry/context-async-hooks@2.6.1"
  - "@opentelemetry/core@2.6.1"
  - "@opentelemetry/resources@2.6.1"
  - "@opentelemetry/sdk-trace-base@2.6.1"
  - "undici@7.24.6"
  - "eslint-plugin-react-hooks@7.0.1"
  - "react-is@19.2.4"
  - "@next/swc-darwin-arm64@16.2.1"
  - "@next/swc-darwin-x64@16.2.1"
  - "@next/swc-linux-arm64-gnu@16.2.1"
  - "@next/swc-linux-arm64-musl@16.2.1"
  - "@next/swc-linux-x64-gnu@16.2.1"
  - "@next/swc-linux-x64-musl@16.2.1"
  - "@next/swc-win32-arm64-msvc@16.2.1"
  - "@next/swc-win32-x64-msvc@16.2.1"
  - "eslint-config-next@16.2.1"
  - "@next/eslint-plugin-next@16.2.1"
  - "@next/env@16.2.1"
  - "next@16.2.1"
  - "@vitest/pretty-format@4.1.2"
  - "@vitest/spy@4.1.2"
  - "@vitest/utils@4.1.2"
  - "@vitest/mocker@4.1.2"
  - "@vitest/runner@4.1.2"
  - "@vitest/snapshot@4.1.2"
  - "@vitest/expect@4.1.2"
  - "vitest@4.1.2"
  - "@vitest/coverage-v8@4.1.2"
  - "path-to-regexp@8.3.0"
  - "lodash@4.17.23"
  - "zod-to-json-schema@3.25.2"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry/cli": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@datadog/native-appsec": false
  "@datadog/native-iast-taint-tracking": false
  "@datadog/native-metrics": false
  core-js: false
  dd-trace: false
  msgpackr-extract: false
  msw: false
  prisma: false
  protobufjs: false
