body:
  - type: textarea
    attributes:
      label: Describe the feature or potential improvement
      description: Please describe the change as clear and concise as possible. Remember to add context as to why you believe this is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the change here. If your idea is related to any issues or discussions, link them here.
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribute
      description: Are you willing to contribute to the implementation of this idea?
      options:
        - label: Yes, I can implement this and raise a PR
