body:
  - type: textarea
    attributes:
      label: Describe your question
      description: Please describe your question as clearly and concisely as possible. Include any relevant context, error messages, or steps to reproduce.
      placeholder: What are you trying to accomplish? What issue are you encountering?
    validations:
      required: true
  - type: dropdown
    id: hosting
    attributes:
      label: Are you using Langfuse Cloud or self-host Langfuse?
      description: This helps us provide more targeted support.
      options:
        - Langfuse Cloud
        - Self-hosted Langfuse
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Pre-submission checks
      description: Please confirm you've checked the following before posting
      options:
        - label: I've searched existing [issues](https://github.com/langfuse/langfuse/issues) and [discussions](https://github.com/orgs/langfuse/discussions)
        - label: I've asked the [Langfuse AI](https://langfuse.com/docs/ask-ai) for help
    validations:
      required: true
