ALTER TABLE traces ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS environment;
ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS environment;
ALTER TABLE scores ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS environment;
