-- Drop materialized views first
DROP VIEW IF EXISTS traces_30d_amt_mv ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};
DROP VIEW IF EXISTS traces_7d_amt_mv ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};
DROP VIEW IF EXISTS traces_all_amt_mv ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};

-- Drop AMT tables
DROP TABLE IF EXISTS traces_30d_amt ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};
DROP TABLE IF EXISTS traces_7d_amt ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};
DROP TABLE IF EXISTS traces_all_amt ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};

-- Drop the Null table
DROP TABLE IF EXISTS traces_null ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME};
