ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} ADD INDEX IF NOT EXISTS idx_res_metadata_key mapKeys(metadata) TYPE bloom_filter(0.01) GRANULARITY 1;
ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} ADD INDEX IF NOT EXISTS idx_res_metadata_value mapValues(metadata) TYPE bloom_filter(0.01) GRANULARITY 1;
ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} MATERIALIZE INDEX IF EXISTS idx_res_metadata_key;
ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} MATERIALIZE INDEX IF EXISTS idx_res_metadata_value;
