ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} DROP INDEX IF EXISTS idx_res_metadata_value;
ALTER TABLE observations ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} DROP INDEX IF EXISTS idx_res_metadata_key;
