ALTER TABLE dataset_run_items_rmt ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} ADD INDEX IF NOT EXISTS idx_trace_id trace_id TYPE bloom_filter(0.001) GRANULARITY 1;
ALTER TABLE dataset_run_items_rmt ON CLUSTER ${CLICKHOUSE_CLUSTER_NAME} MATERIALIZE INDEX IF EXISTS idx_trace_id;
