ALTER TABLE observations ON CLUSTER {CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS usage_pricing_tier_name SETTINGS alter_sync = 2;
ALTER TABLE observations ON CLUSTER {CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS usage_pricing_tier_id SETTINGS alter_sync = 2;
