ALTER TABLE observations ON CLUSTER {CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS usage_pricing_tier_name;
ALTER TABLE observations ON CLUSTER {CLICKHOUSE_CLUSTER_NAME} DROP COLUMN IF EXISTS usage_pricing_tier_id;
