import Decimal from "decimal.js";

export type BatchExportSessionsRow = {
  id: string;
  createdAt: Date;
  bookmarked: boolean;
  public: boolean;
  userIds?: string[] | null;
  countTraces?: number | null;
  sessionDuration?: number | null;
  inputCost?: Decimal | null;
  outputCost?: Decimal | null;
  totalCost?: Decimal | null;
  inputTokens?: bigint | null;
  outputTokens?: bigint | null;
  totalTokens?: bigint | null;
  traceTags?: string[] | null;
  totalCount: number;
};

export type BatchExportTracesRow = {
  bookmarked: boolean;
  id: string;
  timestamp: Date;
  name: string;
  userId?: string | null;
  scores?: Record<string, string[] | number[]> | null;
  release?: string | null;
  version?: string | null;
  sessionId?: string | null;
  input?: unknown | null;
  output?: unknown | null;
  metadata?: unknown | null;
  tags: string[];
};

export type BatchExportEventsRow = {
  id: string;
  traceId: string;
  traceName: string | null;
  type: string;
  name: string;
  startTime: Date;
  endTime: Date | null;
  completionStartTime: Date | null;
  environment: string | null;
  version: string | null;
  userId: string | null;
  sessionId: string | null;
  level: string;
  statusMessage: string | null;
  promptName: string | null;
  promptId: string | null;
  promptVersion: number | null;
  modelId: string | null;
  providedModelName: string | null;
  modelParameters: unknown;
  usageDetails: Record<string, number>;
  costDetails: Record<string, number>;
  totalCost: number | null;
  input: unknown;
  output: unknown;
  metadata: Record<string, unknown>;
  latencyMs: number | null;
  timeToFirstTokenMs: number | null;
  tags: string[];
  release: string | null;
  parentObservationId: string | null;
  scores?: Record<string, string[] | number[]> | null;
  comments: unknown[];
};
