import { z } from "zod";
declare const EnvSchema: z.ZodObject<{
    BUILD_ID: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    DATABASE_URL: z.ZodString;
    HOSTNAME: z.ZodDefault<z.ZodString>;
    PORT: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_S3_BATCH_EXPORT_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_S3_BATCH_EXPORT_BUCKET: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_PREFIX: z.ZodDefault<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_REGION: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_ENDPOINT: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_S3_EVENT_UPLOAD_BUCKET: z.ZodString;
    LANGFUSE_S3_EVENT_UPLOAD_PREFIX: z.ZodDefault<z.ZodString>;
    LANGFUSE_S3_EVENT_UPLOAD_REGION: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    BATCH_EXPORT_ROW_LIMIT: z.ZodDefault<z.ZodNumber>;
    BATCH_EXPORT_DOWNLOAD_LINK_EXPIRATION_HOURS: z.ZodDefault<z.ZodNumber>;
    BATCH_ACTION_EXPORT_ROW_LIMIT: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_MAX_HISTORIC_EVAL_CREATION_LIMIT: z.ZodDefault<z.ZodNumber>;
    EMAIL_FROM_ADDRESS: z.ZodOptional<z.ZodString>;
    SMTP_CONNECTION_URL: z.ZodOptional<z.ZodString>;
    LANGFUSE_INGESTION_QUEUE_PROCESSING_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_INGESTION_SECONDARY_QUEUE_PROCESSING_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_SECONDARY_INGESTION_QUEUE_ENABLED_PROJECT_IDS: z.ZodOptional<z.ZodString>;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_INGESTION_CLICKHOUSE_MAX_ATTEMPTS: z.ZodDefault<z.ZodNumber>;
    REDIS_HOST: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    REDIS_PORT: z.ZodNullable<z.ZodDefault<z.ZodNumber>>;
    REDIS_AUTH: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    REDIS_CONNECTION_STRING: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    REDIS_ENABLE_AUTO_PIPELINING: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    CLICKHOUSE_URL: z.ZodString;
    CLICKHOUSE_USER: z.ZodString;
    CLICKHOUSE_CLUSTER_NAME: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_DB: z.ZodDefault<z.ZodString>;
    CLICKHOUSE_PASSWORD: z.ZodString;
    LANGFUSE_EVAL_CREATOR_WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_TRACE_UPSERT_WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_TRACE_DELETE_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_SCORE_DELETE_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_PROJECT_DELETE_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_EVAL_EXECUTION_WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_EXPERIMENT_CREATOR_WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    STRIPE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_PROJECT_IDS: z.ZodDefault<z.ZodString>;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_MIN_PROJECT_CREATE_DATE: z.ZodOptional<z.ZodString>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodDefault<z.ZodString>;
    OTEL_SERVICE_NAME: z.ZodDefault<z.ZodString>;
    LANGFUSE_ENABLE_BACKGROUND_MIGRATIONS: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_ENABLE_REDIS_SEEN_EVENT_CACHE: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_CLOUD_USAGE_METERING_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_INGESTION_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_BATCH_EXPORT_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_BATCH_ACTION_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_EVAL_EXECUTION_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_TRACE_UPSERT_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_CREATE_EVAL_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_TRACE_DELETE_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_SCORE_DELETE_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_PROJECT_DELETE_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_DATASET_RUN_ITEM_UPSERT_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_EXPERIMENT_CREATE_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_POSTHOG_INTEGRATION_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_INGESTION_SECONDARY_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    QUEUE_CONSUMER_DATA_RETENTION_QUEUE_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_CACHE_MODEL_MATCH_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_CACHE_MODEL_MATCH_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    LANGFUSE_S3_CORE_DATA_EXPORT_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_BUCKET: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_PREFIX: z.ZodDefault<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_REGION: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ENDPOINT: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_CORE_DATA_UPLOAD_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: z.ZodDefault<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_REGION: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_POSTGRES_METERING_DATA_EXPORT_IS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LANGFUSE_S3_CONCURRENT_READS: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    REDIS_PORT: number | null;
    REDIS_ENABLE_AUTO_PIPELINING: "true" | "false";
    CLICKHOUSE_URL: string;
    CLICKHOUSE_CLUSTER_NAME: string;
    CLICKHOUSE_DB: string;
    CLICKHOUSE_USER: string;
    CLICKHOUSE_PASSWORD: string;
    LANGFUSE_S3_EVENT_UPLOAD_BUCKET: string;
    LANGFUSE_S3_EVENT_UPLOAD_PREFIX: string;
    LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true" | "false";
    LANGFUSE_S3_CORE_DATA_EXPORT_IS_ENABLED: "true" | "false";
    LANGFUSE_POSTGRES_METERING_DATA_EXPORT_IS_ENABLED: "true" | "false";
    DATABASE_URL: string;
    HOSTNAME: string;
    PORT: number;
    LANGFUSE_S3_BATCH_EXPORT_ENABLED: "true" | "false";
    LANGFUSE_S3_BATCH_EXPORT_PREFIX: string;
    LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE: "true" | "false";
    BATCH_EXPORT_ROW_LIMIT: number;
    BATCH_EXPORT_DOWNLOAD_LINK_EXPIRATION_HOURS: number;
    BATCH_ACTION_EXPORT_ROW_LIMIT: number;
    LANGFUSE_MAX_HISTORIC_EVAL_CREATION_LIMIT: number;
    LANGFUSE_INGESTION_QUEUE_PROCESSING_CONCURRENCY: number;
    LANGFUSE_INGESTION_SECONDARY_QUEUE_PROCESSING_CONCURRENCY: number;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_BATCH_SIZE: number;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS: number;
    LANGFUSE_INGESTION_CLICKHOUSE_MAX_ATTEMPTS: number;
    LANGFUSE_EVAL_CREATOR_WORKER_CONCURRENCY: number;
    LANGFUSE_TRACE_UPSERT_WORKER_CONCURRENCY: number;
    LANGFUSE_TRACE_DELETE_CONCURRENCY: number;
    LANGFUSE_SCORE_DELETE_CONCURRENCY: number;
    LANGFUSE_PROJECT_DELETE_CONCURRENCY: number;
    LANGFUSE_EVAL_EXECUTION_WORKER_CONCURRENCY: number;
    LANGFUSE_EXPERIMENT_CREATOR_WORKER_CONCURRENCY: number;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_PROJECT_IDS: string;
    OTEL_EXPORTER_OTLP_ENDPOINT: string;
    OTEL_SERVICE_NAME: string;
    LANGFUSE_ENABLE_BACKGROUND_MIGRATIONS: "true" | "false";
    LANGFUSE_ENABLE_REDIS_SEEN_EVENT_CACHE: "true" | "false";
    QUEUE_CONSUMER_CLOUD_USAGE_METERING_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_INGESTION_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_BATCH_EXPORT_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_BATCH_ACTION_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_EVAL_EXECUTION_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_TRACE_UPSERT_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_CREATE_EVAL_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_TRACE_DELETE_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_SCORE_DELETE_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_PROJECT_DELETE_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_DATASET_RUN_ITEM_UPSERT_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_EXPERIMENT_CREATE_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_POSTHOG_INTEGRATION_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_INGESTION_SECONDARY_QUEUE_IS_ENABLED: "true" | "false";
    QUEUE_CONSUMER_DATA_RETENTION_QUEUE_IS_ENABLED: "true" | "false";
    LANGFUSE_CACHE_MODEL_MATCH_ENABLED: "true" | "false";
    LANGFUSE_CACHE_MODEL_MATCH_TTL_SECONDS: number;
    LANGFUSE_S3_CORE_DATA_UPLOAD_PREFIX: string;
    LANGFUSE_S3_CORE_DATA_UPLOAD_FORCE_PATH_STYLE: "true" | "false";
    LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: string;
    LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true" | "false";
    LANGFUSE_S3_CONCURRENT_READS: number;
    REDIS_HOST?: string | null | undefined;
    REDIS_AUTH?: string | null | undefined;
    REDIS_CONNECTION_STRING?: string | null | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    EMAIL_FROM_ADDRESS?: string | undefined;
    SMTP_CONNECTION_URL?: string | undefined;
    BUILD_ID?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_BUCKET?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_REGION?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_ENDPOINT?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_SECONDARY_INGESTION_QUEUE_ENABLED_PROJECT_IDS?: string | undefined;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_MIN_PROJECT_CREATE_DATE?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_BUCKET?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_BUCKET?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
}, {
    CLICKHOUSE_URL: string;
    CLICKHOUSE_USER: string;
    CLICKHOUSE_PASSWORD: string;
    LANGFUSE_S3_EVENT_UPLOAD_BUCKET: string;
    DATABASE_URL: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    REDIS_HOST?: string | null | undefined;
    REDIS_PORT?: number | null | undefined;
    REDIS_AUTH?: string | null | undefined;
    REDIS_CONNECTION_STRING?: string | null | undefined;
    REDIS_ENABLE_AUTO_PIPELINING?: "true" | "false" | undefined;
    CLICKHOUSE_CLUSTER_NAME?: string | undefined;
    CLICKHOUSE_DB?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_PREFIX?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE?: "true" | "false" | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    LANGFUSE_S3_CORE_DATA_EXPORT_IS_ENABLED?: "true" | "false" | undefined;
    LANGFUSE_POSTGRES_METERING_DATA_EXPORT_IS_ENABLED?: "true" | "false" | undefined;
    EMAIL_FROM_ADDRESS?: string | undefined;
    SMTP_CONNECTION_URL?: string | undefined;
    BUILD_ID?: string | undefined;
    HOSTNAME?: string | undefined;
    PORT?: number | undefined;
    LANGFUSE_S3_BATCH_EXPORT_ENABLED?: "true" | "false" | undefined;
    LANGFUSE_S3_BATCH_EXPORT_BUCKET?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_PREFIX?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_REGION?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_ENDPOINT?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE?: "true" | "false" | undefined;
    BATCH_EXPORT_ROW_LIMIT?: number | undefined;
    BATCH_EXPORT_DOWNLOAD_LINK_EXPIRATION_HOURS?: number | undefined;
    BATCH_ACTION_EXPORT_ROW_LIMIT?: number | undefined;
    LANGFUSE_MAX_HISTORIC_EVAL_CREATION_LIMIT?: number | undefined;
    LANGFUSE_INGESTION_QUEUE_PROCESSING_CONCURRENCY?: number | undefined;
    LANGFUSE_INGESTION_SECONDARY_QUEUE_PROCESSING_CONCURRENCY?: number | undefined;
    LANGFUSE_SECONDARY_INGESTION_QUEUE_ENABLED_PROJECT_IDS?: string | undefined;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_BATCH_SIZE?: number | undefined;
    LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS?: number | undefined;
    LANGFUSE_INGESTION_CLICKHOUSE_MAX_ATTEMPTS?: number | undefined;
    LANGFUSE_EVAL_CREATOR_WORKER_CONCURRENCY?: number | undefined;
    LANGFUSE_TRACE_UPSERT_WORKER_CONCURRENCY?: number | undefined;
    LANGFUSE_TRACE_DELETE_CONCURRENCY?: number | undefined;
    LANGFUSE_SCORE_DELETE_CONCURRENCY?: number | undefined;
    LANGFUSE_PROJECT_DELETE_CONCURRENCY?: number | undefined;
    LANGFUSE_EVAL_EXECUTION_WORKER_CONCURRENCY?: number | undefined;
    LANGFUSE_EXPERIMENT_CREATOR_WORKER_CONCURRENCY?: number | undefined;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_PROJECT_IDS?: string | undefined;
    LANGFUSE_SKIP_INGESTION_CLICKHOUSE_READ_MIN_PROJECT_CREATE_DATE?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    OTEL_SERVICE_NAME?: string | undefined;
    LANGFUSE_ENABLE_BACKGROUND_MIGRATIONS?: "true" | "false" | undefined;
    LANGFUSE_ENABLE_REDIS_SEEN_EVENT_CACHE?: "true" | "false" | undefined;
    QUEUE_CONSUMER_CLOUD_USAGE_METERING_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_INGESTION_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_BATCH_EXPORT_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_BATCH_ACTION_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_EVAL_EXECUTION_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_TRACE_UPSERT_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_CREATE_EVAL_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_TRACE_DELETE_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_SCORE_DELETE_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_PROJECT_DELETE_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_DATASET_RUN_ITEM_UPSERT_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_EXPERIMENT_CREATE_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_POSTHOG_INTEGRATION_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_INGESTION_SECONDARY_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    QUEUE_CONSUMER_DATA_RETENTION_QUEUE_IS_ENABLED?: "true" | "false" | undefined;
    LANGFUSE_CACHE_MODEL_MATCH_ENABLED?: "true" | "false" | undefined;
    LANGFUSE_CACHE_MODEL_MATCH_TTL_SECONDS?: number | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_BUCKET?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_PREFIX?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_S3_CORE_DATA_UPLOAD_FORCE_PATH_STYLE?: "true" | "false" | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_BUCKET?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_PREFIX?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_REGION?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY?: string | undefined;
    LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE?: "true" | "false" | undefined;
    LANGFUSE_S3_CONCURRENT_READS?: number | undefined;
}>;
export declare const env: z.infer<typeof EnvSchema>;
export {};
//# sourceMappingURL=env.d.ts.map