// codegen entry: keeps fs/import.meta out of the typechecked pipeline files
import { writeFileSync } from "node:fs";
import { sql } from "./ingest.pipeline.ts";

const out = new URL("../sql/transform-v2.sql", import.meta.url);
writeFileSync(
  out,
  `-- GENERATED by pipeline/ingest.pipeline.ts (node pipeline/gen.mjs) — do not edit\n${sql}`,
);
console.log(`wrote ${out.pathname}`);
