ALTER TABLE traces RESET SETTING enable_block_number_column, enable_block_offset_column;
ALTER TABLE observations RESET SETTING enable_block_number_column, enable_block_offset_column;
ALTER TABLE scores RESET SETTING enable_block_number_column, enable_block_offset_column;
ALTER TABLE dataset_run_items_rmt RESET SETTING enable_block_number_column, enable_block_offset_column;
ALTER TABLE blob_storage_file_log RESET SETTING enable_block_number_column, enable_block_offset_column;
