contact_links:
  - name: 🤗 Get Help
    url: https://github.com/langfuse/langfuse/discussions/new?category=q-a
    about: If you can’t get something to work the way you expect, open a question in our discussion forums.
  - name: 💡 Feature Request
    url: https://github.com/langfuse/langfuse/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
