INSERT INTO langfuse.observations
SELECT toString(randUniform(0, 500000)) AS id,
  toString(floor(randExponential(1 / 2)) % 1000) AS trace_id,
  toString(floor(randExponential(1 / 2)) % 1000) AS project_id,
  multiIf(
    rand() < 0.8,
    'SPAN',
    rand() < 0.95,
    'GENERATION',
    'EVENT'
  ) AS `type`,
  toString(rand()) AS `parent_observation_id`,
  addYears(now(), -1) + number AS `created_at`,
  addHours(addYears(now(), -1), number * 1) AS `start_time`,
  addSeconds(start_time, floor(randExponential(1 / 10))) AS `end_time`,
  concat('name', toString(rand() % 100)) AS `name`,
  map('key', 'value') AS metadata,
  'level' AS `level`,
  'status_message' AS `status_message`,
  'version' AS `version`,
  repeat('input', toInt64(randExponential(1 / 100))) AS `input`,
  repeat('output', toInt64(randExponential(1 / 100))) AS `output`,
  toString(rand() % 1000) AS `model`,
  'internal_model' AS `internal_model`,
  'model_parameters' AS `model_parameters`,
  toInt32(rand() % 1000) AS `prompt_tokens`,
  toInt32(rand() % 1000) AS `completion_tokens`,
  toInt32(rand() % 1000) AS `total_tokens`,
  'unit' AS `unit`,
  rand64() AS `input_cost`,
  rand64() AS `output_cost`,
  rand64() AS `total_cost`,
  addYears(now(), -1) AS `completion_start_time`,
  toString(rand()) AS `prompt_id`,
  now() AS event_ts,
  randUniform(0, 1000000) AS event_microseconds
FROM numbers(1000000);