/**
 * NextJS Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiObservationsPost201ResponseObservation } from '../models/ApiObservationsPost201ResponseObservation';
import { HttpFile } from '../http/http';

export class ApiObservationsPost201Response {
    'success'?: boolean;
    'observation'?: ApiObservationsPost201ResponseObservation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "observation",
            "baseName": "observation",
            "type": "ApiObservationsPost201ResponseObservation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiObservationsPost201Response.attributeTypeMap;
    }

    public constructor() {
    }
}

