/**
 * NextJS Swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiObservationsPost201ResponseObservation {
    'id'?: string;
    'traceId'?: string;
    'type'?: string;
    'name'?: string;
    'startTime'?: Date;
    'endTime'?: Date;
    'attributes'?: { [key: string]: any; };
    'parentObservationId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "traceId",
            "baseName": "traceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "parentObservationId",
            "baseName": "parentObservationId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiObservationsPost201ResponseObservation.attributeTypeMap;
    }

    public constructor() {
    }
}

