-- AlterTable
ALTER TABLE "triggers" ADD COLUMN "last_triggered_at" TIMESTAMP(3);

-- AlterEnum
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PAGERDUTY';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'MICROSOFT_TEAMS';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'JIRA';
