ALTER TYPE "JobConfigBlockReason" RENAME TO "EvaluatorBlockReason";

ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'CONNECTION_AUTH_INVALID' TO 'LLM_CONNECTION_AUTH_INVALID';
ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'CONNECTION_MISSING' TO 'LLM_CONNECTION_MISSING';
ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'DEFAULT_MODEL_MISSING' TO 'DEFAULT_EVAL_MODEL_MISSING';
ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'MODEL_CONFIG_INVALID' TO 'EVAL_MODEL_CONFIG_INVALID';
ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'MODEL_UNAVAILABLE' TO 'EVAL_MODEL_UNAVAILABLE';
ALTER TYPE "EvaluatorBlockReason" RENAME VALUE 'PROVIDER_ACCOUNT_UNREADY' TO 'PROVIDER_ACCOUNT_NOT_READY';
