#!/usr/bin/env node

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { format as formatWithPrettier } from "prettier";

const packageRoot = resolve(new URL("..", import.meta.url).pathname);
const generatedPath = resolve(packageRoot, "src/generated/skills.js");
const sourceApiUrl =
  "https://api.github.com/repos/langfuse/skills/contents/skills/langfuse/references?ref=main";
const isCheckMode = process.argv.includes("--check");

const getGitHubHeaders = () => ({
  Accept: "application/vnd.github+json",
  Authorization: process.env.GITHUB_TOKEN
    ? `Bearer ${process.env.GITHUB_TOKEN}`
    : undefined,
  "User-Agent": "langfuse-sync-skills",
});

const fetchResponse = async (url) => {
  const response = await fetch(url, { headers: getGitHubHeaders() });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  return response;
};

const listRemoteMarkdownFiles = async () => {
  const response = await fetchResponse(sourceApiUrl);
  const entries = await response.json();

  if (!Array.isArray(entries)) {
    throw new Error("Unexpected GitHub API response while listing remote skills");
  }

  return entries
    .filter(
      (entry) =>
        entry.type === "file" &&
        typeof entry.name === "string" &&
        entry.name.endsWith(".md") &&
        typeof entry.download_url === "string",
    )
    .sort((left, right) => left.name.localeCompare(right.name));
};

const parseSkill = (fileName, markdown) => {
  const frontmatterMatch = markdown.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!frontmatterMatch) {
    throw new Error(`${fileName} is missing frontmatter`);
  }

  const metadata = {};
  let currentKey;
  for (const line of frontmatterMatch[1].split("\n")) {
    const match = line.match(/^([a-z_]+):\s*(.*)$/);
    if (match) {
      currentKey = match[1];
      metadata[currentKey] = match[2];
    } else if (currentKey === "description" && line.trim()) {
      metadata.description += ` ${line.trim()}`;
    }
  }

  for (const key of ["name", "description"]) {
    if (
      metadata[key]?.startsWith("'") &&
      metadata[key]?.endsWith("'")
    ) {
      metadata[key] = metadata[key].slice(1, -1).replaceAll("''", "'");
    }
  }
  if (
    !metadata ||
    typeof metadata !== "object" ||
    Array.isArray(metadata) ||
    typeof metadata.name !== "string" ||
    typeof metadata.description !== "string"
  ) {
    throw new Error(`${fileName} has invalid skill metadata`);
  }

  const instructions = markdown.slice(frontmatterMatch[0].length).trim();
  if (!instructions) {
    throw new Error(`${fileName} is missing instructions`);
  }

  return {
    name: metadata.name,
    description: metadata.description,
    instructions,
  };
};

const getExpectedSkills = async () => {
  const remoteFiles = await listRemoteMarkdownFiles();
  return Promise.all(
    remoteFiles.map(async ({ name, download_url: downloadUrl }) => {
      const markdown = await (await fetchResponse(downloadUrl)).text();
      return parseSkill(name, markdown);
    }),
  );
};

const renderGeneratedModule = async (skills) =>
  formatWithPrettier(
    `// This file is generated by packages/langfuse-skills/scripts/sync-skills.mjs.
// Do not edit it manually.

exports.LANGFUSE_SKILLS = [
${skills
  .map(
    (skill) =>
      `  ${JSON.stringify(skill)},`,
  )
  .join("\n")}
];
`,
    { parser: "babel" },
  );

const main = async () => {
  const expectedSkills = await getExpectedSkills();
  const expectedModule = await renderGeneratedModule(expectedSkills);

  if (isCheckMode) {
    try {
      if (readFileSync(generatedPath, "utf8") !== expectedModule) {
        throw new Error("Generated skill catalog differs from upstream");
      }
    } catch (error) {
      if (error.code === "ENOENT") {
        throw new Error("Generated skill catalog is missing");
      }
      throw error;
    }

    console.log(
      `Generated Langfuse skills are in sync: ${expectedSkills
        .map(({ name }) => name)
        .join(", ")}`,
    );
    return;
  }

  mkdirSync(resolve(packageRoot, "src/generated"), { recursive: true });
  writeFileSync(generatedPath, expectedModule);
  console.log(`Synced ${expectedSkills.length} Langfuse skills.`);
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
