#!/usr/bin/env bash
#
# Generates a production-ready .env file for docker-compose.yml by replacing
# every value marked "# CHANGEME" with a strong, randomly generated secret.
#
# docker-compose.yml is never modified: `docker compose` reads a .env file
# in the same directory automatically and substitutes it into the
# ${VAR:-default} placeholders already present in that file.
#
# Usage:
#   scripts/generate-prod-secrets.sh --domain https://langfuse.example.com [--output .env] [--force]
#
# Re-running without --force on an existing output file preserves secrets
# that are already set and only fills in what's missing, so it's safe to
# use for rotating a single value by deleting it from .env first.

set -euo pipefail

DOMAIN=""
OUTPUT=".env"
FORCE=0

usage() {
  echo "Usage: $0 --domain <https://your-domain> [--output .env] [--force]" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "$DOMAIN" ]]; then
  echo "Error: --domain is required, e.g. --domain https://langfuse.example.com" >&2
  usage
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required but was not found on PATH." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE_FILE="$REPO_ROOT/.env.prod.example"

if [[ ! -f "$EXAMPLE_FILE" ]]; then
  echo "Error: $EXAMPLE_FILE not found. Run this script from a langfuse checkout." >&2
  exit 1
fi

if [[ -f "$OUTPUT" && "$FORCE" -ne 1 ]]; then
  echo "Notice: $OUTPUT already exists. Preserving existing values, filling in only what's missing."
  echo "        Use --force to start from a clean template instead."
fi

# Alphanumeric secret: safe to embed unescaped in a Postgres connection URL,
# a docker-compose YAML scalar, and shell env assignment without quoting.
random_alnum() {
  local bytes="$1"
  openssl rand -base64 "$bytes" | tr -dc 'A-Za-z0-9' | head -c "$((bytes * 2))"
}

random_hex() {
  local bytes="$1"
  openssl rand -hex "$bytes"
}

declare -A EXISTING=()
if [[ -f "$OUTPUT" ]]; then
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    EXISTING["$key"]="$value"
  done < <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$OUTPUT" || true)
fi

get_or_generate() {
  local key="$1"
  local generator="$2"
  if [[ "$FORCE" -ne 1 && -n "${EXISTING[$key]:-}" ]]; then
    echo "${EXISTING[$key]}"
  else
    eval "$generator"
  fi
}

POSTGRES_USER="postgres"
POSTGRES_DB="postgres"
POSTGRES_PASSWORD="$(get_or_generate POSTGRES_PASSWORD 'random_alnum 24')"
DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

CLICKHOUSE_USER="clickhouse"
CLICKHOUSE_PASSWORD="$(get_or_generate CLICKHOUSE_PASSWORD 'random_alnum 24')"

REDIS_AUTH="$(get_or_generate REDIS_AUTH 'random_alnum 24')"

# MinIO has a single root user shared by the event/media/batch-export
# credentials in docker-compose.yml (all three access key IDs default to
# "minio"), so the secret access keys must match MINIO_ROOT_PASSWORD.
MINIO_ROOT_USER="minio"
MINIO_ROOT_PASSWORD="$(get_or_generate MINIO_ROOT_PASSWORD 'random_alnum 32')"

NEXTAUTH_SECRET="$(get_or_generate NEXTAUTH_SECRET 'random_alnum 32')"
SALT="$(get_or_generate SALT 'random_alnum 32')"
ENCRYPTION_KEY="$(get_or_generate ENCRYPTION_KEY 'random_hex 32')"

{
  echo "# Generated by scripts/generate-prod-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# DO NOT COMMIT THIS FILE. Keep it out of version control and back it up securely."
  echo
  echo "NEXTAUTH_URL=${DOMAIN}"
  echo
  echo "DATABASE_URL=${DATABASE_URL}"
  echo "POSTGRES_USER=${POSTGRES_USER}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "POSTGRES_DB=${POSTGRES_DB}"
  echo
  echo "SALT=${SALT}"
  echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}"
  echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}"
  echo
  echo "CLICKHOUSE_USER=${CLICKHOUSE_USER}"
  echo "CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}"
  echo
  echo "REDIS_AUTH=${REDIS_AUTH}"
  echo
  echo "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
  echo "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
  echo "LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${MINIO_ROOT_USER}"
  echo "LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}"
  echo "LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=${MINIO_ROOT_USER}"
  echo "LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}"
  echo "LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=${MINIO_ROOT_USER}"
  echo "LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}"
} > "$OUTPUT"

chmod 600 "$OUTPUT"

cat <<EOF

Wrote secrets to $OUTPUT (mode 600).

Every "# CHANGEME" value in docker-compose.yml is now covered. Not touched
by this script, review manually before going live:
  - EMAIL_FROM_ADDRESS / SMTP_CONNECTION_URL (transactional email)
  - TLS termination in front of langfuse-web (this script does not add a
    reverse proxy)
  - Firewall rules restricting inbound access to ports 3000 and 9090 per
    the comment at the top of docker-compose.yml
  - Off-host backups for the named volumes (postgres, clickhouse, minio)

Start the stack with:
  docker compose --env-file $OUTPUT up -d
EOF
