import { execFile } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import {
  IndentationText,
  Project,
  QuoteKind,
  VariableDeclarationKind,
} from "ts-morph";
import { format } from "prettier";

const execFileAsync = promisify(execFile);

const PACKAGE_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const SKILLS_REPO_URL = "https://github.com/langfuse/skills.git";
const SKILLS_REPO_COMMIT = "c39789078b848160a695947907db3ba40b7a2bce";
const GENERATED_SOURCE_DIR = path.join(PACKAGE_ROOT, "src/generated");
const DEFAULT_TOKEN_PATTERN = /[a-z0-9]+/g;
const GENERATED_HEADER =
  "// This file is generated by packages/skill-index/scripts/generate.mjs. Do not edit.";
const OUT_OF_DATE_MESSAGE =
  "@langfuse/skill-index generated files are out of date. Run pnpm --filter @langfuse/skill-index run generate.";

const WHITELISTED_FILE_PATHS = [
  "skills/langfuse/references/error-analysis.md",
  "skills/langfuse/references/instrumentation.md",
  "skills/langfuse/references/judge-calibration.md",
];

const SKILL_MODULES = Object.freeze(
  Object.fromEntries(
    WHITELISTED_FILE_PATHS.map((relativePath) => {
      const { normalizedPath } = validateWhitelistedPath(relativePath);
      const skillId = path.basename(normalizedPath, ".md");
      const moduleName = getSkillModuleName(skillId);
      return [
        skillId,
        {
          importName: `${moduleName.replaceAll("-", "_").toUpperCase()}_SKILL`,
          moduleSpecifier: `./skills/${moduleName}`,
        },
      ];
    }),
  ),
);

/** @typedef {{ id: string; title: string; content: string }} Skill */
/** @typedef {{ normalizedPath: string; absolutePath: string }} ValidatedPath */
/** @typedef {{ heading: string; startLine: number; endLine: number; content: string }} MarkdownChunk */

/**
 * @param {unknown} relativePath
 * @param {string} sourceRoot
 * @returns {ValidatedPath}
 */
function validateWhitelistedPath(relativePath, sourceRoot = ".") {
  if (typeof relativePath !== "string" || relativePath.length === 0) {
    throw new Error("Whitelist entries must be non-empty strings.");
  }

  if (path.isAbsolute(relativePath)) {
    throw new Error(`Whitelist entry must be relative: ${relativePath}`);
  }

  const parts = relativePath.split(/[\\/]/);
  if (parts.includes("..")) {
    throw new Error(
      `Whitelist entry must not traverse directories: ${relativePath}`,
    );
  }

  if (path.extname(relativePath) !== ".md") {
    throw new Error(`Whitelist entry must be a Markdown file: ${relativePath}`);
  }

  const normalizedPath = path.normalize(relativePath);
  const absolutePath = path.resolve(sourceRoot, normalizedPath);
  const relativeToRoot = path.relative(sourceRoot, absolutePath);

  if (relativeToRoot.startsWith("..") || path.isAbsolute(relativeToRoot)) {
    throw new Error(
      `Whitelist entry must stay inside skill sources: ${relativePath}`,
    );
  }

  return {
    normalizedPath: normalizedPath.replaceAll(path.sep, "/"),
    absolutePath,
  };
}

/**
 * @param {string} content
 * @param {string} relativePath
 */
function getTitle(content, relativePath) {
  const title = content.match(/^#\s+(.+)$/m)?.[1]?.trim();
  return title || path.basename(relativePath, ".md");
}

async function buildSkillIndexData() {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "langfuse-skills-"));

  try {
    await execFileAsync("git", ["init", tempRoot]);
    await execFileAsync("git", [
      "-C",
      tempRoot,
      "remote",
      "add",
      "origin",
      SKILLS_REPO_URL,
    ]);
    await execFileAsync("git", [
      "-C",
      tempRoot,
      "fetch",
      "--depth=1",
      "origin",
      SKILLS_REPO_COMMIT,
    ]);
    await execFileAsync("git", [
      "-C",
      tempRoot,
      "checkout",
      "--detach",
      "FETCH_HEAD",
    ]);

    /** @type {Skill[]} */
    const skills = [];

    for (const entry of WHITELISTED_FILE_PATHS) {
      const { normalizedPath, absolutePath } = validateWhitelistedPath(
        entry,
        tempRoot,
      );
      const content = await readFile(absolutePath, "utf8");
      const id = path.basename(normalizedPath, ".md");
      const title = getTitle(content, normalizedPath);
      skills.push({ id, title, content });
    }

    return createSkillIndexData(skills);
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
}

/**
 * @param {Skill[]} skills
 */
function createSkillIndexData(skills) {
  const chunks = skills.flatMap((skill) =>
    splitMarkdown(skill.content).map((chunk, index) => {
      const tokens = tokenizeBm25Text(`${skill.title} ${chunk.content}`);

      return {
        id: `${skill.id}-${index + 1}`,
        skillIndex: skill.id,
        title: skill.title,
        heading: chunk.heading,
        index,
        startLine: chunk.startLine,
        endLine: chunk.endLine,
        content: chunk.content,
        terms: termCounts(tokens),
        length: tokens.length,
      };
    }),
  );

  const documentFrequency = Object.create(null);
  for (const chunk of chunks) {
    for (const term of Object.keys(chunk.terms)) {
      documentFrequency[term] = (documentFrequency[term] ?? 0) + 1;
    }
  }

  const documentCount = chunks.length || 1;
  const idf = Object.fromEntries(
    Object.entries(documentFrequency).map(([term, frequency]) => [
      term,
      Math.log(1 + (documentCount - frequency + 0.5) / (frequency + 0.5)),
    ]),
  );
  const averageDocumentLength =
    chunks.reduce((sum, chunk) => sum + chunk.length, 0) / documentCount;

  return {
    skills,
    chunks,
    search: { averageDocumentLength, idf },
  };
}

/**
 * @param {string} content
 * @returns {MarkdownChunk[]}
 */
function splitMarkdown(content) {
  const lines = content.split("\n");
  const chunks = [];
  let startLine = 1;
  let heading = "Overview";
  let current = [];
  let inCodeFence = false;

  const flush = (endLine) => {
    const text = current.join("\n").trim();
    if (text) {
      chunks.push({ heading, startLine, endLine, content: text });
    }
  };

  lines.forEach((line, index) => {
    const isFence = /^\s*(```|~~~)/.test(line);
    const match = inCodeFence ? null : line.match(/^(#{1,3})\s+(.+)$/);
    if (match && current.length > 0) {
      flush(index);
      current = [];
      startLine = index + 1;
      heading = match[2]?.trim() ?? heading;
    } else if (match) {
      heading = match[2]?.trim() ?? heading;
      startLine = index + 1;
    }
    current.push(line);
    if (isFence) {
      inCodeFence = !inCodeFence;
    }
  });

  flush(lines.length);
  return chunks;
}

/**
 * @param {string[]} tokens
 */
function termCounts(tokens) {
  return tokens.reduce((counts, token) => {
    counts[token] = (counts[token] ?? 0) + 1;
    return counts;
  }, Object.create(null));
}

/**
 * @param {string} text
 */
function tokenizeBm25Text(text) {
  return text.toLowerCase().match(DEFAULT_TOKEN_PATTERN) ?? [];
}

async function buildGeneratedFiles(data) {
  const files = new Map();
  const searchIndex = {
    chunks: data.chunks,
    search: data.search,
  };

  files.set(
    path.join(GENERATED_SOURCE_DIR, "README.md"),
    `# Generated Skill Index\n\nDo not edit files in this directory by hand.\n\nThese files are generated by \`packages/skill-index/scripts/generate.mjs\` from the pinned external skill source. To update them, change the generator or its pinned inputs, then run:\n\n\`\`\`bash\npnpm --filter @langfuse/skill-index run generate\n\`\`\`\n`,
  );

  files.set(
    path.join(GENERATED_SOURCE_DIR, "search-index.ts"),
    await buildSearchIndexOutput(searchIndex),
  );

  for (const skill of data.skills) {
    files.set(
      path.join(
        GENERATED_SOURCE_DIR,
        "skills",
        `${getSkillModuleName(skill.id)}.ts`,
      ),
      await buildSkillOutput(skill),
    );
  }

  files.set(
    path.join(GENERATED_SOURCE_DIR, "skill-loaders.ts"),
    await buildSkillLoadersOutput(data.skills),
  );

  return files;
}

function createGeneratedSourceFile(filePath) {
  const project = new Project({
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      quoteKind: QuoteKind.Double,
    },
  });

  return project.createSourceFile(filePath, "");
}

async function getGeneratedSourceText(sourceFile) {
  return format(`${GENERATED_HEADER}\n${sourceFile.getFullText()}`, {
    parser: "typescript",
  });
}

function addJsonConst(sourceFile, { name, type, initializer, isExported }) {
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported,
    declarations: [
      {
        name,
        type,
        initializer: JSON.stringify(initializer, null, 2),
      },
    ],
  });
}

async function buildSearchIndexOutput(searchIndex) {
  const sourceFile = createGeneratedSourceFile("search-index.ts");

  sourceFile.addImportDeclaration({
    isTypeOnly: true,
    namedImports: ["SkillSearchIndexData"],
    moduleSpecifier: "../runtime",
  });

  addJsonConst(sourceFile, {
    name: "SKILL_SEARCH_INDEX",
    type: "SkillSearchIndexData",
    initializer: searchIndex,
    isExported: true,
  });

  return getGeneratedSourceText(sourceFile);
}

async function buildSkillOutput(skill) {
  const sourceFile = createGeneratedSourceFile(
    `${getSkillModuleName(skill.id)}.ts`,
  );

  sourceFile.addImportDeclaration({
    isTypeOnly: true,
    namedImports: ["SkillIndexSkill"],
    moduleSpecifier: "../../runtime",
  });

  addJsonConst(sourceFile, {
    name: "SKILL",
    type: "SkillIndexSkill",
    initializer: skill,
    isExported: true,
  });

  return getGeneratedSourceText(sourceFile);
}

/**
 * @param {Skill[]} skills
 */
async function buildSkillLoadersOutput(skills) {
  const sourceFile = createGeneratedSourceFile("skill-loaders.ts");
  const skillIds = skills.map((skill) => skill.id);

  sourceFile.addImportDeclaration({
    isTypeOnly: true,
    namedImports: ["SkillIndexSkill"],
    moduleSpecifier: "../runtime",
  });

  for (const skill of skills) {
    const skillModule = SKILL_MODULES[skill.id];
    sourceFile.addImportDeclaration({
      namedImports: [{ name: "SKILL", alias: skillModule.importName }],
      moduleSpecifier: skillModule.moduleSpecifier,
    });
  }

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    isExported: true,
    declarations: [
      {
        name: "LANGFUSE_SKILL_IDS",
        initializer: `${JSON.stringify(skillIds, null, 2)} as const`,
      },
    ],
  });

  sourceFile.addTypeAlias({
    isExported: true,
    name: "LangfuseSkillId",
    type: "(typeof LANGFUSE_SKILL_IDS)[number]",
  });

  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: "SKILL_LOADERS",
        initializer: (writer) => {
          writer
            .inlineBlock(() => {
              for (const skill of skills) {
                const skillModule = SKILL_MODULES[skill.id];
                writer.writeLine(
                  `${JSON.stringify(skill.id)}: async () => ${skillModule.importName},`,
                );
              }
            })
            .write(
              " satisfies Record<LangfuseSkillId, () => Promise<SkillIndexSkill>>",
            );
        },
      },
    ],
  });

  sourceFile.addFunction({
    isExported: true,
    name: "isLangfuseSkillId",
    parameters: [{ name: "id", type: "string" }],
    returnType: "id is LangfuseSkillId",
    statements: ["return LANGFUSE_SKILL_IDS.includes(id as LangfuseSkillId);"],
  });

  sourceFile.addFunction({
    isAsync: true,
    isExported: true,
    name: "loadSkill",
    parameters: [{ name: "id", type: "LangfuseSkillId" }],
    returnType: "Promise<SkillIndexSkill>",
    statements: ["return SKILL_LOADERS[id]();"],
  });

  return getGeneratedSourceText(sourceFile);
}

/**
 * @param {string} skillId
 */
function getSkillModuleName(skillId) {
  if (!/^[a-z0-9-]+$/.test(skillId)) {
    throw new Error(
      `Skill id is not safe for a generated module name: ${skillId}`,
    );
  }

  return skillId;
}

/**
 * @param {string} directory
 * @returns {Promise<string[]>}
 */
async function listGeneratedFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true }).catch(
    (error) => {
      if (
        error &&
        typeof error === "object" &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        return [];
      }
      throw error;
    },
  );

  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return listGeneratedFiles(entryPath);
      }
      return entry.isFile() ? [entryPath] : [];
    }),
  );

  return files.flat();
}

export async function generateSkillIndex({ check = false } = {}) {
  const data = await buildSkillIndexData();
  const generatedFiles = await buildGeneratedFiles(data);

  if (check) {
    const expectedPaths = new Set(generatedFiles.keys());
    const existingPaths = new Set(
      await listGeneratedFiles(GENERATED_SOURCE_DIR),
    );

    for (const [filePath, sourceOutput] of generatedFiles) {
      const existingSource = await readFile(filePath, "utf8").catch(() => null);
      if (existingSource !== sourceOutput) {
        throw new Error(OUT_OF_DATE_MESSAGE);
      }
    }

    for (const filePath of existingPaths) {
      if (!expectedPaths.has(filePath)) {
        throw new Error(OUT_OF_DATE_MESSAGE);
      }
    }

    if (existingPaths.size !== expectedPaths.size) {
      throw new Error(OUT_OF_DATE_MESSAGE);
    }

    console.log("@langfuse/skill-index generated files are up to date.");
    return;
  }

  await rm(GENERATED_SOURCE_DIR, { recursive: true, force: true });
  for (const [filePath, sourceOutput] of generatedFiles) {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, sourceOutput);
  }
  console.log("Generated @langfuse/skill-index source files.");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await generateSkillIndex({ check: process.argv.includes("--check") });
}
