ALTER TYPE "EvalTemplateType" ADD VALUE IF NOT EXISTS 'FACET';

ALTER TABLE "evaluators"
  ADD COLUMN IF NOT EXISTS "is_built_in" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "evaluation_rules"
  ADD COLUMN IF NOT EXISTS "idle_time" INTEGER;
