import type { NextApiRequest, NextApiResponse } from "next";
import { getJacksonInstance, logger } from "@langfuse/shared/src/server";

/**
 * SP (Service Provider) metadata endpoint for SAML SSO.
 *
 * Returns the SAML SP metadata XML generated by Jackson. IdP administrators
 * need this to configure their side of the SAML connection.
 */
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  try {
    if (req.method !== "GET") {
      res.status(405).json({ error: "Method Not Allowed" });
      return;
    }

    const jackson = await getJacksonInstance();
    const { spConfig } = jackson;

    const metadataXml = await spConfig.toXMLMetadata();

    res.setHeader("Content-Type", "text/xml; charset=utf-8");
    res.status(200).send(metadataXml);
  } catch (error) {
    logger.error("Error fetching SAML SP metadata:", error);
    res.status(500).json({ error: "Internal Server Error" });
  }
}
