/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A snapshot of one finalized event row, retained until its JS handle and any encoder tasks drop it. */
export declare class PreparedEvent {
  /**
   * Read a storage-ready row into owned Rust fields. JSON-valued String columns such as
   * `model_parameters` must already be serialized by TypeScript; `event_bytes` must be supplied
   * after overflow handling and accounting. This constructor never serializes the JS row.
   */
  constructor(row: object)
  get ids(): PreparedEventIds
  static columns(): Array<PreparedEventColumn>
}

/**
 * Encode prepared event handles as Native blocks.
 *
 * The array is the batch merge point. Each handle already owns an immutable typed row, so the
 * async task only clones its Arc and never reads or copies row fields.
 */
export declare function encodeClickhouseEvents(rows: PreparedEvent[], maxRowsPerBlock: number): Promise<NativeEventBlock[]>

/**
 * Hello-world entry point. It proves that the worker can load and call the
 * addon and that native code reports through the same telemetry as the rest
 * of the worker: one increment of the `langfuse.native.hello_calls` counter
 * tagged with `source`, plus a debug-level log line. The worker calls this on
 * every health probe, so the log line stays below the default level.
 */
export declare function hello(source: string): void

/**
 * Installs the metrics exporter and the log subscriber for native code. Call
 * it once at process start; later calls return the first call's outcome.
 */
export declare function initTelemetry(options?: TelemetryOptions | undefined | null): void

/**
 * A complete ClickHouse Native request body and its row count.
 *
 * The buffer is created only after the async Rust encoder has finished. The JS transport can
 * retain it for retries without retaining the input rows or any NAPI handles.
 */
export interface NativeEventBlock {
  bytes: Buffer
  rowCount: number
}

/** ClickHouse column metadata generated from the prepared-row schema. */
export interface PreparedEventColumn {
  name: string
  columnType: string
  usesDefault: boolean
}

/** Identifiers used by ingestion retry and drop logging. */
export interface PreparedEventIds {
  project_id: string
  trace_id: string
  id: string
}

/**
 * Overrides for [`init_telemetry`]. Everything left unset comes from the
 * environment: `DD_DOGSTATSD_HOST` / `DD_AGENT_HOST` and `DD_DOGSTATSD_PORT`
 * for the agent, `DD_ENV`, `DD_SERVICE`, `DD_VERSION`, `DD_TAGS` for global
 * tags, `LANGFUSE_LOG_LEVEL`, `LANGFUSE_LOG_FORMAT` and `RUST_LOG` for logs.
 */
export interface TelemetryOptions {
  /** DogStatsD endpoint as `host:port`. */
  dogstatsdAddress?: string
  /** How often aggregated metrics are flushed to the agent, in milliseconds. */
  flushIntervalMs?: number
}
