/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class EarlyOtelBatch {
  /** Release this path's source ownership after all legacy/direct consumers have finished. */
  dispose(): Promise<void>
  /** Only the compact document crosses into JS for legacy or TS direct processing. */
  json(): string
  get media(): Array<ExtractedOtelMedia>
  /** Decode one upload at a time without keeping every decoded body alive. */
  mediaBody(index: number): Promise<Buffer>
  /** Failed uploads restore only the selected occurrence; successful ones use the service ID. */
  originalMedia(index: number): Promise<string>
}

/** A snapshot of one finalized event row, retained until its JS handle and any encoder tasks drop it. */
export declare class PreparedEvent {
  /**
   * Read a storage-ready row into owned Rust fields. JSON-valued String columns such as
   * `model_parameters` must already be serialized by TypeScript; `event_bytes` must be supplied
   * after overflow handling and accounting. This constructor never serializes the JS row.
   */
  constructor(row: object)
  get ids(): PreparedEventIds
  static columns(): Array<PreparedEventColumn>
}

export declare class ValidatedOtelJson {
  /** Release a superseded masking input without waiting for the JS handle to be collected. */
  dispose(): Promise<void>
  /** Compact the accepted document; media ranges retain its source until both write paths finish. */
  extract(enabled: boolean): Promise<EarlyOtelBatch>
}

/**
 * Fits topic clusters and a separate 2D display projection in memory.
 * This is CPU-bound and synchronous; call it in a killable child process.
 */
export declare function clusterTopicEmbeddings(embeddings: Array<Array<number>>, settings: TopicClusteringSettings): TopicClusteringResult

/**
 * Encode prepared event handles as Native blocks.
 *
 * The array is the batch merge point. Each handle already owns an immutable typed row, so the
 * async task only clones its Arc and never reads or copies row fields.
 */
export declare function encodeClickhouseEvents(rows: PreparedEvent[], maxRowsPerBlock: number): Promise<NativeEventBlock[]>

export interface ExtractedOtelMedia {
  index: number
  reference: string
  contentType: string
  sha256Hash: string
  kind: string
  originalByteLength: number
}

/**
 * Hello-world entry point. It proves that the worker can load and call the
 * addon and that native code reports through the same telemetry as the rest
 * of the worker: one increment of the `langfuse.native.hello_calls` counter
 * tagged with `source`, plus a debug-level log line. The worker calls this on
 * every health probe, so the log line stays below the default level.
 */
export declare function hello(source: string): void

/**
 * Installs the metrics exporter and the log subscriber for native code. Call
 * it once at process start; later calls return the first call's outcome.
 */
export declare function initTelemetry(options?: TelemetryOptions | undefined | null): void

/**
 * A complete ClickHouse Native request body and its row count.
 *
 * The buffer is created only after the async Rust encoder has finished. The JS transport can
 * retain it for retries without retaining the input rows or any NAPI handles.
 */
export interface NativeEventBlock {
  bytes: Buffer
  rowCount: number
}

/** ClickHouse column metadata generated from the prepared-row schema. */
export interface PreparedEventColumn {
  name: string
  columnType: string
  usesDefault: boolean
}

/** Identifiers used by ingestion retry and drop logging. */
export interface PreparedEventIds {
  project_id: string
  trace_id: string
  id: string
}

/**
 * Overrides for [`init_telemetry`]. Everything left unset comes from the
 * environment: `DD_DOGSTATSD_HOST` / `DD_AGENT_HOST` and `DD_DOGSTATSD_PORT`
 * for the agent, `DD_ENV`, `DD_SERVICE`, `DD_VERSION`, `DD_TAGS` for global
 * tags, `LANGFUSE_LOG_LEVEL`, `LANGFUSE_LOG_FORMAT` and `RUST_LOG` for logs.
 */
export interface TelemetryOptions {
  /** DogStatsD endpoint as `host:port`. */
  dogstatsdAddress?: string
  /** How often aggregated metrics are flushed to the agent, in milliseconds. */
  flushIntervalMs?: number
}

export interface TopicClusteringResult {
  status: string
  labels: Array<number>
  coordinates: Array<Array<number>>
}

export interface TopicClusteringSettings {
  minimumCount: number
  minClusterSize: number
  /** Number of neighboring samples, excluding the sample itself. */
  minSamples: number
}

/**
 * Snapshot bytes once on the JS thread. Only Rust-owned memory reaches the validator task;
 * retaining a mutable Node Buffer across an async read would not enforce that ownership.
 */
export declare function validateOtelJson(bytes: Buffer, discoverMedia?: boolean | undefined | null): Promise<ValidatedOtelJson>
