// Turns reviewer findings into the review-tests output, in the one format the
// skill posts. Pure: every link is resolved through an injected `link(file,
// line)` so the same finding renders as a repo-relative link locally and a
// head-SHA GitHub permalink when posting.
//
// A comment never names an axiom and never carries an em or en dash; model text
// is sanitized here so a reviewer's stray dash cannot reach a PR. Three shapes:
//
//   delete            first line "**Remove this test.**", then one evidence line
//                     linking the covering test and why dropping it loses nothing.
//   delete that folds  first line "**Fold this test into [survivor](url).**",
//                     then the reason; the paired edit lives on that survivor.
//   edit              the ```suggestion``` block first, then the explanation, then
//                     a "Folds in ..." line linking any deleted tests it absorbs.
//
// Local (default) prints the summary and the findings grouped by file.
// `buildPostPayload` returns the summary comment and one inline comment per
// finding, each anchored at its `(file, line)` and footered. A survivor whose
// line is outside the PR diff cannot take an inline comment; the caller reposts
// that comment's body as an ordinary PR comment, where its permalink still
// resolves.

const FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_";

const labelFor = ({ file, line }) => `${file.split("/").pop()}:${line}`;
const mdLink = (loc, link) => `[${labelFor(loc)}](${link(loc.file, loc.line)})`;

// A reader acts on the reviewer's prose, so an em or en dash it slipped in
// becomes a comma rather than being dropped; hyphens are left untouched.
const clean = (text) => (text ?? "").replace(/\s*[—–]\s*/g, ", ").trim();

/**
 * The body of one finding's comment, without the footer.
 * @param {object} finding
 * @param {(file: string, line: number) => string} link
 * @returns {string}
 */
export function commentBody(finding, link) {
  const comment = clean(finding.comment);
  if (finding.verdict === "edit") {
    const parts = ["```suggestion", finding.suggestion, "```", "", comment];
    const absorbs = finding.absorbs ?? [];
    if (absorbs.length) {
      parts.push(
        "",
        `Folds in ${absorbs.map((a) => mdLink(a, link)).join(", ")}.`,
      );
    }
    return parts.join("\n");
  }
  if (finding.fold) {
    return `**Fold this test into ${mdLink(finding.coveredBy, link)}.**\n\n${comment}`;
  }
  const evidence = `Covered by ${mdLink(finding.coveredBy, link)}.`;
  return `**Remove this test.**\n\n${comment ? `${evidence} ${comment}` : evidence}`;
}

/** The one-line summary. `flagged` is the sum of removals and fixes. */
export function summaryLine({ reviewed, findings }) {
  const deletes = findings.filter((f) => f.verdict === "delete").length;
  const edits = findings.filter((f) => f.verdict === "edit").length;
  return `**review-tests**: reviewed ${reviewed}, flagged ${deletes + edits} (${deletes} to remove, ${edits} to fix). Details inline.`;
}

const byLine = (a, b) => a.line - b.line;

/** The chat output: the summary, findings grouped by file, one footer. */
export function renderLocal({ findings, reviewed, link }) {
  const summary = summaryLine({ reviewed, findings });
  if (!findings.length) return `${summary}${FOOTER}`;

  const files = new Map();
  for (const f of findings) {
    if (!files.has(f.file)) files.set(f.file, []);
    files.get(f.file).push(f);
  }
  const sections = [...files.keys()].sort().map((file) => {
    const bodies = files
      .get(file)
      .sort(byLine)
      .map((f) => `:${f.line}\n${commentBody(f, link)}`)
      .join("\n\n");
    return `## ${file}\n\n${bodies}`;
  });
  return `${summary}\n\n${sections.join("\n\n")}${FOOTER}`;
}

/**
 * The PR review: a footered summary comment and one footered inline comment per
 * finding, each anchored at the finding's own `(file, line)`.
 */
export function buildPostPayload({ findings, reviewed, permalink }) {
  return {
    summary: `${summaryLine({ reviewed, findings })}${FOOTER}`,
    comments: findings.map((f) => ({
      path: f.file,
      line: f.line,
      body: `${commentBody(f, permalink)}${FOOTER}`,
    })),
  };
}
