import assert from "node:assert/strict";
import test from "node:test";

import {
  buildPostPayload,
  commentBody,
  renderLocal,
  summaryLine,
} from "./report.mjs";

const link = (file, line) => `https://x/${file}#L${line}`;
const FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_";

test("a plain delete leads with Remove and one evidence line linking the survivor", () => {
  const body = commentBody(
    {
      verdict: "delete",
      file: "web/a.test.ts",
      line: 10,
      comment: "same fixture, same rejection assertion",
      coveredBy: { file: "web/b.test.ts", line: 88 },
      fold: false,
    },
    link,
  );
  assert.equal(
    body,
    "**Remove this test.**\n\n" +
      "Covered by [b.test.ts:88](https://x/web/b.test.ts#L88). same fixture, same rejection assertion",
  );
});

test("a fold delete points at the survivor it consolidates into", () => {
  const body = commentBody(
    {
      verdict: "delete",
      file: "web/a.test.ts",
      line: 10,
      comment: "its null-token case is the only unique input here",
      coveredBy: { file: "web/b.test.ts", line: 88 },
      fold: true,
    },
    link,
  );
  assert.equal(
    body,
    "**Fold this test into [b.test.ts:88](https://x/web/b.test.ts#L88).**\n\n" +
      "its null-token case is the only unique input here",
  );
});

test("an edit puts the suggestion block first, then the explanation and folded-in links", () => {
  const body = commentBody(
    {
      verdict: "edit",
      file: "web/b.test.ts",
      line: 88,
      comment: "assert the returned value, not the spy",
      suggestion:
        'it("rejects expired and null", () => {\n  expect(v(t)).toBe(false);\n});',
      absorbs: [{ file: "web/a.test.ts", line: 10 }],
    },
    link,
  );
  assert.equal(
    body,
    "```suggestion\n" +
      'it("rejects expired and null", () => {\n  expect(v(t)).toBe(false);\n});\n' +
      "```\n\n" +
      "assert the returned value, not the spy\n\n" +
      "Folds in [a.test.ts:10](https://x/web/a.test.ts#L10).",
  );
});

test("an edit with nothing to absorb omits the folds-in line", () => {
  const body = commentBody(
    {
      verdict: "edit",
      file: "web/b.test.ts",
      line: 88,
      comment: "collapse the five-currency case list to one row",
      suggestion: "it.each([[usd]])(...)",
      absorbs: [],
    },
    link,
  );
  assert.equal(
    body,
    "```suggestion\nit.each([[usd]])(...)\n```\n\ncollapse the five-currency case list to one row",
  );
});

test("em and en dashes in model text are replaced, hyphens are left alone", () => {
  const body = commentBody(
    {
      verdict: "delete",
      file: "a.test.ts",
      line: 1,
      comment: "well-formed already — the sibling covers it – nothing new",
      coveredBy: { file: "b.test.ts", line: 2 },
      fold: false,
    },
    link,
  );
  assert.ok(!/[—–]/.test(body), "no em or en dash survives");
  assert.ok(body.includes("well-formed already"), "the hyphen is untouched");
});

test("the summary counts removals and fixes", () => {
  const findings = [
    { verdict: "delete" },
    { verdict: "delete" },
    { verdict: "edit" },
  ];
  assert.equal(
    summaryLine({ reviewed: 9, findings }),
    "**review-tests**: reviewed 9, flagged 3 (2 to remove, 1 to fix). Details inline.",
  );
});

test("the local render groups by file, opens with the summary, ends with one footer", () => {
  const findings = [
    {
      verdict: "delete",
      file: "web/b.test.ts",
      line: 88,
      comment: "covered upstream",
      coveredBy: { file: "web/c.test.ts", line: 4 },
      fold: false,
    },
    {
      verdict: "edit",
      file: "web/a.test.ts",
      line: 10,
      comment: "assert the row",
      suggestion: "it(...)",
      absorbs: [],
    },
  ];
  const out = renderLocal({ findings, reviewed: 5, link });
  assert.ok(
    out.startsWith(
      "**review-tests**: reviewed 5, flagged 2 (1 to remove, 1 to fix).",
    ),
  );
  assert.ok(out.includes("web/a.test.ts"));
  assert.ok(out.includes("web/b.test.ts"));
  assert.ok(out.endsWith(FOOTER));
  assert.equal(out.match(/Generated by/g).length, 1, "one footer only");
});

test("the post payload carries a footered summary and one footered inline comment per finding", () => {
  const findings = [
    {
      verdict: "delete",
      file: "web/a.test.ts",
      line: 10,
      comment: "covered",
      coveredBy: { file: "web/b.test.ts", line: 88 },
      fold: false,
    },
  ];
  const payload = buildPostPayload({ findings, reviewed: 3, permalink: link });
  assert.ok(payload.summary.endsWith(FOOTER));
  assert.equal(payload.comments.length, 1);
  assert.deepEqual(
    { path: payload.comments[0].path, line: payload.comments[0].line },
    { path: "web/a.test.ts", line: 10 },
  );
  assert.ok(payload.comments[0].body.startsWith("**Remove this test.**"));
  assert.ok(payload.comments[0].body.endsWith(FOOTER));
});
