-- GENERATED by pipeline/ingest.pipeline.ts (node pipeline/gen.mjs) — do not edit
INSERT INTO {STAGING}
    (project_id, trace_id, span_id, parent_span_id, start_time, end_time, name, type, environment, version, release, trace_name, user_id, session_id, level, status_message, prompt_name, prompt_version, provided_model_name, provided_usage_details, usage_details, input, output, metadata_names, metadata_values, source, service_name, service_version, scope_name, scope_version, telemetry_sdk_language, telemetry_sdk_name, telemetry_sdk_version, blob_storage_file_path, event_bytes, event_ts, span_kind, has_media, media_manifest)
WITH
    resource_spans AS (
        SELECT
            json AS rs,
            _path AS source_file,
            extract(_path, 'otel-poc[^/]*/([^/]+)/') AS project_id
        FROM s3('{URL}', '{S3_ACCESS_KEY}', '{S3_SECRET_KEY}', 'JSONAsObject', 'json JSON')
    ),
    scopes AS (
        SELECT
            source_file AS source_file,
            project_id AS project_id,
            arrayMap(x -> ifNull(x.key.:String, ''), rs.resource.attributes[]) AS res_keys,
            arrayMap(x -> ifNull(x.value.stringValue.:String, ''), rs.resource.attributes[]) AS res_vals,
            arrayJoin(rs.scopeSpans[]) AS ss
        FROM resource_spans
    ),
    spans AS (
        SELECT
            source_file AS source_file,
            project_id AS project_id,
            res_keys AS res_keys,
            res_vals AS res_vals,
            ifNull(ss.scope.name.:String, '') AS scope_name,
            ifNull(ss.scope.version.:String, '') AS scope_version,
            arrayJoin(ss.spans[]) AS sp
        FROM scopes
    ),
    parsed AS (
        SELECT
            source_file AS source_file,
            project_id AS project_id,
            res_keys AS res_keys,
            res_vals AS res_vals,
            scope_name AS scope_name,
            scope_version AS scope_version,
            ifNull(sp.traceId.:String, lower(hex(arrayStringConcat(arrayMap(x -> char(x), CAST(sp.traceId.data, 'Array(UInt8)')))))) AS trace_id,
            ifNull(sp.spanId.:String, lower(hex(arrayStringConcat(arrayMap(x -> char(x), CAST(sp.spanId.data, 'Array(UInt8)')))))) AS span_id,
            ifNull(sp.parentSpanId.:String, lower(hex(arrayStringConcat(arrayMap(x -> char(x), CAST(sp.parentSpanId.data, 'Array(UInt8)')))))) AS parent_span_id,
            if(sp.startTimeUnixNano.:String IS NOT NULL, toUInt64OrZero(assumeNotNull(sp.startTimeUnixNano.:String)), ((toUInt64(ifNull(accurateCastOrNull(sp.startTimeUnixNano.high, 'Int64'), 0)) * 4294967296) + toUInt64(bitAnd(ifNull(accurateCastOrNull(sp.startTimeUnixNano.low, 'Int64'), 0), 4294967295)))) AS start_ns,
            if(sp.endTimeUnixNano.:String IS NOT NULL, toUInt64OrZero(assumeNotNull(sp.endTimeUnixNano.:String)), ((toUInt64(ifNull(accurateCastOrNull(sp.endTimeUnixNano.high, 'Int64'), 0)) * 4294967296) + toUInt64(bitAnd(ifNull(accurateCastOrNull(sp.endTimeUnixNano.low, 'Int64'), 0), 4294967295)))) AS end_ns,
            ifNull(sp.name.:String, '') AS name,
            toUInt8(ifNull(accurateCastOrNull(sp.kind, 'Int64'), 0)) AS span_kind,
            ifNull(sp.status.message.:String, '') AS status_message,
            arrayMap(x -> ifNull(x.key.:String, ''), sp.attributes[]) AS attr_keys,
            arrayMap(x -> ifNull(x.value.stringValue.:String, ''), sp.attributes[]) AS attr_vals,
            arrayMap(x -> multiIf(x.value.intValue.:String IS NOT NULL, toInt64OrZero(assumeNotNull(x.value.intValue.:String)), accurateCastOrNull(x.value.intValue.low, 'Int64') IS NOT NULL, ((ifNull(accurateCastOrNull(x.value.intValue.high, 'Int64'), 0) * 4294967296) + bitAnd(assumeNotNull(accurateCastOrNull(x.value.intValue.low, 'Int64')), 4294967295)), ifNull(accurateCastOrNull(x.value.intValue, 'Int64'), 0)), sp.attributes[]) AS attr_ivals,
            arrayMap(x -> ifNull(accurateCastOrNull(x.value.doubleValue, 'Float64'), 0), sp.attributes[]) AS attr_dvals
        FROM spans
    ),
    enriched AS (
        SELECT
            project_id AS project_id,
            scope_name AS scope_name,
            scope_version AS scope_version,
            trace_id AS trace_id,
            span_id AS span_id,
            parent_span_id AS parent_span_id,
            fromUnixTimestamp64Nano(toInt64(start_ns)) AS start_time,
            fromUnixTimestamp64Nano(toInt64(end_ns)) AS end_time,
            name AS name,
            span_kind AS span_kind,
            status_message AS status_message,
            attr_vals[indexOf(attr_keys, 'langfuse.observation.type')] AS type,
            res_vals[indexOf(res_keys, 'service.name')] AS service_name,
            res_vals[indexOf(res_keys, 'service.version')] AS service_version,
            res_vals[indexOf(res_keys, 'telemetry.sdk.language')] AS telemetry_sdk_language,
            res_vals[indexOf(res_keys, 'telemetry.sdk.name')] AS telemetry_sdk_name,
            res_vals[indexOf(res_keys, 'telemetry.sdk.version')] AS telemetry_sdk_version,
            if((res_vals[indexOf(res_keys, 'deployment.environment')] = ''), 'default', res_vals[indexOf(res_keys, 'deployment.environment')]) AS environment,
            attr_vals[indexOf(attr_keys, 'gen_ai.request.model')] AS provided_model_name,
            attr_vals[indexOf(attr_keys, 'langfuse.user.id')] AS user_id,
            attr_vals[indexOf(attr_keys, 'langfuse.session.id')] AS session_id,
            attr_vals[indexOf(attr_keys, 'langfuse.trace.name')] AS trace_name,
            attr_vals[indexOf(attr_keys, 'langfuse.release')] AS release,
            attr_vals[indexOf(attr_keys, 'langfuse.version')] AS version,
            attr_vals[indexOf(attr_keys, 'langfuse.observation.level')] AS level,
            attr_vals[indexOf(attr_keys, 'langfuse.prompt.name')] AS prompt_name,
            CAST(nullIf(attr_ivals[indexOf(attr_keys, 'langfuse.prompt.version')], 0), 'Nullable(UInt16)') AS prompt_version,
            mapFilter((k, v) -> (v != 0), CAST((['input', 'output', 'total'], [toUInt64(greatest(attr_ivals[indexOf(attr_keys, 'gen_ai.usage.input_tokens')], 0)), toUInt64(greatest(attr_ivals[indexOf(attr_keys, 'gen_ai.usage.output_tokens')], 0)), toUInt64(greatest(attr_ivals[indexOf(attr_keys, 'gen_ai.usage.total_tokens')], 0))]), 'Map(LowCardinality(String), UInt64)')) AS provided_usage_details,
            attr_vals[indexOf(attr_keys, 'langfuse.observation.input')] AS input_raw,
            attr_vals[indexOf(attr_keys, 'langfuse.observation.output')] AS output,
            toUInt8(match(attr_vals[indexOf(attr_keys, 'langfuse.observation.input')], 'data:[a-zA-Z0-9.+-]+/[a-zA-Z0-9.+-]+;base64,')) AS is_media_candidate,
            arrayFilter(x -> NOT (has(['langfuse.observation.input', 'langfuse.observation.output', 'langfuse.observation.type', 'langfuse.observation.level', 'gen_ai.request.model', 'langfuse.user.id', 'langfuse.session.id', 'langfuse.trace.name', 'langfuse.release', 'langfuse.version', 'langfuse.prompt.name', 'langfuse.prompt.version', 'gen_ai.usage.input_tokens', 'gen_ai.usage.output_tokens', 'gen_ai.usage.total_tokens'], attr_keys[x])), arrayEnumerate(attr_keys)) AS meta_idx,
            arrayMap(x -> if(startsWith(attr_keys[x], 'langfuse.observation.metadata.'), substring(attr_keys[x], 31), attr_keys[x]), meta_idx) AS metadata_names,
            arrayMap(x -> multiIf((attr_vals[x] != ''), attr_vals[x], (attr_ivals[x] != 0), toString(attr_ivals[x]), (attr_dvals[x] != 0), toString(attr_dvals[x]), ''), meta_idx) AS metadata_values,
            source_file AS source_file
        FROM parsed
    ),
    media AS (
        SELECT
            project_id AS project_id,
            trace_id AS trace_id,
            span_id AS span_id,
            parent_span_id AS parent_span_id,
            start_time AS start_time,
            end_time AS end_time,
            name AS name,
            type AS type,
            environment AS environment,
            version AS version,
            release AS release,
            trace_name AS trace_name,
            user_id AS user_id,
            session_id AS session_id,
            level AS level,
            status_message AS status_message,
            prompt_name AS prompt_name,
            prompt_version AS prompt_version,
            provided_model_name AS provided_model_name,
            provided_usage_details AS provided_usage_details,
            output AS output,
            metadata_names AS metadata_names,
            metadata_values AS metadata_values,
            scope_name AS scope_name,
            scope_version AS scope_version,
            service_name AS service_name,
            service_version AS service_version,
            telemetry_sdk_language AS telemetry_sdk_language,
            telemetry_sdk_name AS telemetry_sdk_name,
            telemetry_sdk_version AS telemetry_sdk_version,
            span_kind AS span_kind,
            source_file AS source_file,
            if(is_media_candidate, extractAllGroupsVertical(input_raw, 'data:([a-zA-Z0-9.+-]+/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=]+)'), []) AS media_matches,
            if(is_media_candidate, splitByRegexp('data:[a-zA-Z0-9.+-]+/[a-zA-Z0-9.+-]+;base64,[A-Za-z0-9+/=]+', input_raw), [input_raw]) AS frags,
            arrayMap(x -> replaceAll(replaceAll(base64Encode(SHA256(tryBase64Decode(x[2]))), '+', '-'), '/', '_'), media_matches) AS media_ids,
            arrayMap((x, y) -> concat('@@@langfuseMedia:type=', x[1], '|id=', y, '|source=base64_data_uri@@@'), media_matches, media_ids) AS tokens,
            arrayMap(x -> toUInt32((13 + length(x[1]) + length(x[2]))), media_matches) AS match_lens,
            arrayCumSum(arrayMap(x -> length(x), frags)) AS cum_frag_lens,
            arrayCumSum(match_lens) AS cum_match_lens,
            arrayMap(x -> toUInt32((cum_frag_lens[x] + if((x > 1), cum_match_lens[(x - 1)], 0))), arrayEnumerate(media_matches)) AS offsets
        FROM enriched
    ),
    final AS (
        SELECT
            project_id AS project_id,
            trace_id AS trace_id,
            span_id AS span_id,
            parent_span_id AS parent_span_id,
            start_time AS start_time,
            end_time AS end_time,
            name AS name,
            type AS type,
            environment AS environment,
            version AS version,
            release AS release,
            trace_name AS trace_name,
            user_id AS user_id,
            session_id AS session_id,
            level AS level,
            status_message AS status_message,
            prompt_name AS prompt_name,
            prompt_version AS prompt_version,
            provided_model_name AS provided_model_name,
            provided_usage_details AS provided_usage_details,
            provided_usage_details AS usage_details,
            arrayStringConcat(arrayMap(x -> concat(frags[x], if((x <= length(tokens)), tokens[x], '')), arrayEnumerate(frags))) AS input,
            output AS output,
            metadata_names AS metadata_names,
            metadata_values AS metadata_values,
            'otel' AS source,
            service_name AS service_name,
            service_version AS service_version,
            scope_name AS scope_name,
            scope_version AS scope_version,
            telemetry_sdk_language AS telemetry_sdk_language,
            telemetry_sdk_name AS telemetry_sdk_name,
            telemetry_sdk_version AS telemetry_sdk_version,
            source_file AS blob_storage_file_path,
            toUInt64((length(input) + length(output) + length(name) + arraySum(arrayMap(x -> length(x), metadata_values)))) AS event_bytes,
            now64(6) AS event_ts,
            span_kind AS span_kind,
            toUInt8(length(media_matches) > 0) AS has_media,
            arrayMap(x -> (media_ids[x], media_matches[x][1], 'input', offsets[x], match_lens[x]), arrayEnumerate(media_matches)) AS media_manifest
        FROM media
    )
SELECT project_id, trace_id, span_id, parent_span_id, start_time, end_time, name, type, environment, version, release, trace_name, user_id, session_id, level, status_message, prompt_name, prompt_version, provided_model_name, provided_usage_details, usage_details, input, output, metadata_names, metadata_values, source, service_name, service_version, scope_name, scope_version, telemetry_sdk_language, telemetry_sdk_name, telemetry_sdk_version, blob_storage_file_path, event_bytes, event_ts, span_kind, has_media, media_manifest
FROM final
SETTINGS log_comment = 'poc-chlb-transform-v2'
