ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE} ADD INDEX IF NOT EXISTS idx_session_id session_id TYPE bloom_filter() GRANULARITY 1{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE} MATERIALIZE INDEX IF EXISTS idx_session_id{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS mutations_sync = 2};{CLICKHOUSE_HISTORICAL_FINAL_NEWLINES:0}
