ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS environment{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS environment{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
ALTER TABLE scores {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS environment{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
