-- Drop materialized views first
DROP VIEW IF EXISTS traces_30d_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};
DROP VIEW IF EXISTS traces_7d_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};
DROP VIEW IF EXISTS traces_all_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};

-- Drop AMT tables
DROP TABLE IF EXISTS traces_30d_amt {CLICKHOUSE_CLUSTER_CLAUSE};
DROP TABLE IF EXISTS traces_7d_amt {CLICKHOUSE_CLUSTER_CLAUSE};
DROP TABLE IF EXISTS traces_all_amt {CLICKHOUSE_CLUSTER_CLAUSE};

-- Drop the Null table
DROP TABLE IF EXISTS traces_null {CLICKHOUSE_CLUSTER_CLAUSE};
