ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP INDEX IF EXISTS idx_res_metadata_value{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP INDEX IF EXISTS idx_res_metadata_key{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
