-- Drop materialized views derived from traces_null table
DROP VIEW IF EXISTS traces_all_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};
DROP VIEW IF EXISTS traces_7d_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};
DROP VIEW IF EXISTS traces_30d_amt_mv {CLICKHOUSE_CLUSTER_CLAUSE};{CLICKHOUSE_HISTORICAL_FINAL_NEWLINES:0}
