-- Drop traces_null and trace amt tables
DROP TABLE IF EXISTS traces_null {CLICKHOUSE_CLUSTER_CLAUSE};
DROP TABLE IF EXISTS traces_all_amt {CLICKHOUSE_CLUSTER_CLAUSE};
DROP TABLE IF EXISTS traces_7d_amt {CLICKHOUSE_CLUSTER_CLAUSE};
DROP TABLE IF EXISTS traces_30d_amt {CLICKHOUSE_CLUSTER_CLAUSE};{CLICKHOUSE_HISTORICAL_FINAL_NEWLINES:0}
