ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS usage_pricing_tier_name{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS usage_pricing_tier_id{CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
