ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS tool_definitions SETTINGS alter_sync = 2;
ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS tool_calls SETTINGS alter_sync = 2;
ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP COLUMN IF EXISTS tool_call_names SETTINGS alter_sync = 2;
