ALTER TABLE scores {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS ingestion_sdk_version
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};

ALTER TABLE scores {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS ingestion_sdk_name
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};

ALTER TABLE scores {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS ingestion_api_key
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
