ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE} DROP INDEX IF EXISTS idx_created_at;
ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE} DROP INDEX IF EXISTS idx_created_at;
ALTER TABLE scores {CLICKHOUSE_CLUSTER_CLAUSE} DROP INDEX IF EXISTS idx_created_at;
