name: Build and Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - .pulumi/**
      - config/**
      - src/**

  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        type: choice
        default: staging
        options:
          - staging
          - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment || 'staging' }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
    uses: fulldiveVR/ai-wayz-infrastructure/.github/workflows/deploy-stack-gs.yaml@main
    with:
      service: "ai-stats"
      env: ${{ github.event.inputs.environment || 'staging' }}
      platform: "nodejs"
      telegram-notify-bot-chat: "-985701161"
      docker-file: ./web/Dockerfile
    secrets:
      gcp-credentials-json: "${{ github.event.inputs.environment == 'prod' && secrets.GCP_CREDENTIALS_JSON ||  github.event.inputs.environment == 'prod-ru' && secrets.GCP_CREDENTIALS_PRODRU_JSON || secrets.GCP_CREDENTIALS_STAGING_JSON }}"
      pat-github: "${{ secrets.TOKEN_FOR_SUB }}"
