name: Onboarding Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint Bash & Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install linters (shellcheck + shfmt)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          curl -sSLo shfmt https://github.com/mvdan/sh/releases/latest/download/shfmt_linux_amd64
          chmod +x shfmt && sudo mv shfmt /usr/local/bin

      - name: Run Makefile linter
        run: make lint
