"on":
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    paths:
    - '**'
    - '!.github/workflows/porter_**'
    
name: Deploy to Preview Environment
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Build and deploy preview environment
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml --preview
      env:
        PORTER_CLUSTER: 4037
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 12565
        PORTER_STACK_NAME: web
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_12565_4037 }}
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_REPO_NAME: ${{ github.event.repository.name }}