"on":
  push:
    branches:
      - production
name: Deploy to worker (US)
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply
        env:
          PORTER_CLUSTER: "4038"
          PORTER_DEPLOYMENT_TARGET_ID: 260cd04e-5dc8-4b22-a291-ad4453f981f7
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "12565"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_STACK_NAME: worker
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_STACK_12565_4038 }}
