name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - name: Validate PR title follows conventional commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure the types of commits allowed
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Allow scopes (optional)
          requireScope: false
          # Disallow uppercase in subject
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Configure that a scope may contain slashes, useful for monorepos
          scopes: |
            tracing
            evalQueue
            annotation-queues-ui
            peek
            dataset-runs
            datasets
            traces-api
            cloud
            evals
            dataset-run-items
            otel
            runs-compare
            cursor
          # Allow any scope (not just the ones listed above)
          validateSingleCommit: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request