name: Prettier Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  prettier-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm ci
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: ${{ github.event.pull_request.head.repo.full_name != 'langfuse/langfuse' }}
          prettier_options: ${{ github.event.pull_request.head.repo.full_name != 'langfuse/langfuse' && '--check' || '--write' }} ./src *.{ts,js} --ignore-path .gitignore
          commit_message: "Applied prettier formatting" # only applies to langfuse/langfuse and not to forks
