on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - "v3.[0-9]+.[0-9]+" # Semantic version tags

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: "protected branches"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main # Always checkout main even for tagged releases
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Push to production
        run: git push "https://x-access-token:${GH_ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" +main:production
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
