name: Snyk Container – Web
on:
  push:
    branches: ["*"]

jobs:
  security-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Scan public image with Snyk
        uses: snyk/actions/docker@master
        continue-on-error: true # let upload step always run
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: langfuse/langfuse # pulled from Docker Hub
          args: --severity-threshold=high # (any extra CLI flags, but NO --file)

      - name: Upload SARIF to GH Code Scanning
        if: always() && hashFiles('snyk.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif # produced automatically
          category: web
