name: Snyk Container - Worker
on:
  push:
    branches:
      - "*"

jobs:
  security-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: langfuse/langfuse-worker
          args: --file=worker/Dockerfile --sarif-file-output=snyk-worker.sarif
          
      - name: Upload result to GitHub Code Scanning
        if: always() && hashFiles('snyk-worker.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-worker.sarif
          category: worker